spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.56.10:3306/pms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
  application:
    name: mall-product
  thymeleaf:
    cache: false
  redis:
    host: 192.168.56.10
mybatis-plus:
  mapper-locations: /mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto #自增主键
      logic-delete-value: 0
      logic-not-delete-value: 1
server:
  port: 10000
logging:
  level:
    com.example: debug