spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.56.10:3306/sms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
  application:
    name: mall-coupon
mybatis-plus:
  mapper-locations: /mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto #自增主键
server:
  port: 7000