server:
  port: 40000
spring:
  application:
    name: mall-cart
  redis:
    host: 192.168.56.10
  session:
    store-type: redis

#配置线程池
mall:
  thread:
    coreSize: 20
    maxSize: 200
    keepAliveTime: 10